# Copy this to .settings.yaml and fill it out.

# Screeps account info
# Your username is your full email address.
screeps_username:
screeps_password:
screeps_ptr: false

# Proxy configuration
http_proxy:
http_proxy_port:


# Introduces a small delay between messages to emulate smooth scrolling.
smooth_scroll: true
