# Copy this to .settings.yaml and fill it out.

# Screeps account info
# Your username is your full email address.
screeps_username:
screeps_password:
screeps_ptr: false

# Set a hostname to connect to a private server (e.g. localhost:21025)
screeps_host:

# Proxy configuration
http_proxy:
http_proxy_port:


# Introduces a small delay between messages to emulate smooth scrolling.
smooth_scroll: true

# Once the output buffer reaches this length it will start removing old messages
max_scroll: 200000

# Defines the maximum commands saved to the history file
max_history: 200000
